# Generated by Django 5.1.3 on 2024-11-26 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_comment_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="ad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="api.ad",
            ),
        ),
    ]
